version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/todoapp?schema=public
    depends_on:
      - postgres
    command: pnpm --filter api dev

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api
    command: pnpm --filter web dev

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules: 